name: Stable version build
on:
  push:
    branches:  [ master,init]

jobs:
#  lint:
#    name: "Lint"
#    runs-on: ubuntu-latest
#    steps:
#      - name: set up go 1.18
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.18
#        id: go
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: install golangci-lint and goveralls
#        run: |
#          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.46.2
#      - name: run linters
#        run: $GITHUB_WORKSPACE/golangci-lint run --config .golangci.yml ./...
  push_to_registry:
    name: Push to Docker Actions
    runs-on: ubuntu-latest
#    needs: lint
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to repo
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.TOKENGH }}
          registry: docker.pkg.github.com
          repository: brotherhood228/bro-bot/stable
          tag_with_ref: true